from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('lojas/', views.store_list, name='store_list'),
    path('lojas/<slug:slug>/', views.store_detail, name='store_detail'),
    path('presentes/', views.product_list, name='product_list'),
    path('lojas/<slug:store_slug>/produtos/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('conta/criar/', views.register, name='register'),
    path('conta/entrar/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('conta/sair/', auth_views.LogoutView.as_view(), name='logout'),
    path('conta/recuperar/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('conta/recuperar/enviado/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('conta/redefinir/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('conta/redefinir/concluido/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('conta/destino/', views.post_login, name='post_login'),
    path('conta/perfil/', views.profile, name='profile'),
    path('conta/enderecos/', views.address_list, name='address_list'),
    path('conta/enderecos/novo/', views.address_form, name='address_create'),
    path('conta/enderecos/<int:pk>/editar/', views.address_form, name='address_edit'),
    path('conta/enderecos/<int:pk>/remover/', views.address_delete, name='address_delete'),
    path('carrinho/', views.cart_detail, name='cart_detail'),
    path('carrinho/adicionar/<int:product_id>/', views.cart_add, name='cart_add'),
    path('carrinho/item/<int:item_id>/', views.cart_update, name='cart_update'),
    path('carrinho/loja/<int:store_id>/selecionar/', views.cart_store_toggle, name='cart_store_toggle'),
    path('checkout/', views.checkout, name='checkout'),
    path('pedidos/', views.order_list, name='order_list'),
    path('pedidos/<str:code>/sucesso/', views.order_success, name='order_success'),
    path('pedidos/<str:code>/', views.order_detail, name='order_detail'),
    path('pedidos/<str:code>/avaliar/', views.review_order, name='review_order'),
    path('vendedor/', views.seller_dashboard, name='seller_dashboard'),
    path('vendedor/pedidos/', views.seller_order_list, name='seller_order_list'),
    path('vendedor/pedidos/<str:code>/', views.seller_order_detail, name='seller_order_detail'),
    path('vendedor/pedidos/<str:code>/status/', views.seller_order_transition, name='seller_order_transition'),
    path('vendedor/produtos/', views.seller_product_list, name='seller_product_list'),
    path('vendedor/produtos/novo/', views.seller_product_form, name='seller_product_create'),
    path('vendedor/produtos/<int:pk>/editar/', views.seller_product_form, name='seller_product_edit'),
    path('vendedor/produtos/<int:pk>/alternar/', views.seller_product_toggle, name='seller_product_toggle'),
    path('vendedor/loja/', views.seller_store_edit, name='seller_store_edit'),
    path('vendedor/loja/areas/nova/', views.seller_area_form, name='seller_area_create'),
    path('vendedor/loja/areas/<int:pk>/editar/', views.seller_area_form, name='seller_area_edit'),
    path('vendedor/loja/areas/<int:pk>/remover/', views.seller_area_delete, name='seller_area_delete'),
    path('gestao/', views.staff_dashboard, name='staff_dashboard'),
]
