# Generated by Django 6.0.7 on 2026-07-31 13:50

import django.core.validators
import django.db.models.deletion
import iflower.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('icon', models.CharField(default='bi-flower1', max_length=40, verbose_name='ícone Bootstrap')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='nome do endereço')),
                ('recipient_name', models.CharField(max_length=120, verbose_name='nome do destinatário')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='telefone do destinatário')),
                ('postal_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=150, verbose_name='rua')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='bairro')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('reference', models.CharField(blank=True, max_length=180, verbose_name='ponto de referência')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'ordering': ['-is_primary', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='código público')),
                ('address_snapshot', models.TextField(verbose_name='endereço utilizado')),
                ('recipient_name', models.CharField(max_length=120, verbose_name='nome do destinatário')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='telefone do destinatário')),
                ('delivery_date', models.DateField(verbose_name='data da entrega')),
                ('delivery_period', models.CharField(choices=[('morning', 'Manhã — 08h às 12h'), ('afternoon', 'Tarde — 12h às 18h'), ('evening', 'Noite — 18h às 21h')], max_length=12, verbose_name='período')),
                ('card_message', models.TextField(blank=True, max_length=500, verbose_name='mensagem do cartão')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='pedido anônimo')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='observações')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='taxa de entrega')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto simulado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('payment_method', models.CharField(choices=[('pix', 'Pix simulado'), ('card', 'Cartão simulado'), ('delivery', 'Pagamento na entrega simulado')], max_length=12, verbose_name='forma de pagamento')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado (simulado)'), ('refunded', 'Estornado (simulado)')], max_length=12, verbose_name='status do pagamento')),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('accepted', 'Pedido aceito'), ('preparing', 'Em preparação'), ('ready', 'Pronto para entrega'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('refused', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status do pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iflower.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('short_description', models.CharField(max_length=180, verbose_name='descrição curta')),
                ('description', models.TextField(verbose_name='descrição completa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço promocional')),
                ('image', models.ImageField(blank=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), iflower.models.validate_image_size], verbose_name='imagem principal')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='estoque simulado')),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=45, verbose_name='tempo de preparo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='iflower.category')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140, verbose_name='nome do produto')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='imagem')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('customizations', models.JSONField(blank=True, default=dict, verbose_name='personalizações')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='observações')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iflower.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iflower.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('option_type', models.CharField(choices=[('select', 'Seleção'), ('text', 'Texto'), ('boolean', 'Sim ou não')], default='select', max_length=10, verbose_name='tipo')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatória')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor adicional')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='opções disponíveis')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='iflower.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('selected_customizations', models.JSONField(blank=True, default=dict, verbose_name='personalizações')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='observação')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('additional_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor adicional')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='iflower.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iflower.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), iflower.models.validate_image_size])),
                ('alt_text', models.CharField(max_length=180, verbose_name='texto alternativo')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='iflower.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('vendor', 'Vendedor')], default='client', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pix', 'Pix simulado'), ('card', 'Cartão simulado'), ('delivery', 'Pagamento na entrega simulado')], max_length=12, verbose_name='forma')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado (simulado)'), ('refunded', 'Estornado (simulado)')], max_length=12)),
                ('fake_identifier', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='identificador fictício')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovação simulada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='iflower.order')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('accepted', 'Pedido aceito'), ('preparing', 'Em preparação'), ('ready', 'Pronto para entrega'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('refused', 'Recusado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='iflower.order')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'históricos de status',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, upload_to='stores/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), iflower.models.validate_image_size])),
                ('cover', models.ImageField(blank=True, upload_to='stores/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), iflower.models.validate_image_size])),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('address', models.CharField(max_length=180, verbose_name='endereço')),
                ('opening_hours', models.CharField(default='Seg–Sáb, 08h às 19h', max_length=120, verbose_name='horário de funcionamento')),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=45, verbose_name='tempo médio de preparo')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido mínimo')),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa de entrega')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='nota média')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de avaliações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('is_featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='nota')),
                ('comment', models.TextField(max_length=800, verbose_name='comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('is_approved', models.BooleanField(default=True, verbose_name='aprovada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='iflower.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='iflower.store')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='iflower.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='iflower.store'),
        ),
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iflower.store'),
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='bairro')),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa adicional')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='iflower.store')),
            ],
            options={
                'ordering': ['city', 'neighborhood'],
                'constraints': [models.UniqueConstraint(fields=('store', 'city', 'neighborhood'), name='unique_service_area')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='unique_product_slug_per_store'),
        ),
    ]
