# Generated by Django 6.0.7 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflower', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_item_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_positive_quantity'),
        ),
    ]
