# Generated by Django 6.0.7 on 2026-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflower', '0002_cartitem_cart_item_positive_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_selected',
            field=models.BooleanField(default=True, verbose_name='selecionado para checkout'),
        ),
    ]
