# Generated by Django 6.0.7 on 2026-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflower', '0003_cartitem_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='auto_accept_orders',
            field=models.BooleanField(
                default=True,
                help_text='No MVP, aceita o pedido assim que o checkout é concluído.',
                verbose_name='confirmar pedidos automaticamente',
            ),
        ),
    ]
